### ISSUE TITLE
Random Azure SignalR Exception when killing a client App and NOT firing the OnDisconnect on server side hub.

### ISSUE THREAD

**Issue by digitalkirkley** [Azure/azure-signalr#1013]
### URGENT HELP REQUIRED PLEASE: Random Azure SignalR Exception when killing a client App and NOT firing the OnDisconnect on server side hub.  Server side has a single hub on 4 Kubernetes pod instances which all connect to the single Azure SignalR Service.  Each .NET Core 3.1 App at startup sets the ApplicationName by using the environment machinename removing the "-" as part of name validation (This is the Pod name from Kubernetes). 

  2020-08-28T15:45:28.41206759Z [40m[37mdbug[39m[22m[49m: Microsoft.Azure.SignalR.Connections.Client.Internal.WebSocketsTransport[13]
  2020-08-28T15:45:28.41207089Z       Received message from application. Payload size: 28.
  2020-08-28T15:45:28.41207389Z [40m[37mdbug[39m[22m[49m: Microsoft.Azure.SignalR.Connections.Client.Internal.WebSocketsTransport[13]
  2020-08-28T15:45:28.412118089Z       Received message from application. Payload size: 28.
  2020-08-28T15:45:28.412125189Z [40m[37mdbug[39m[22m[49m: Microsoft.Azure.SignalR.Connections.Client.Internal.WebSocketsTransport[12]
  2020-08-28T15:45:28.412128289Z       Message received. Type: Binary, size: 3, EndOfMessage: True.
  2020-08-28T15:45:28.412131089Z [40m[37mdbug[39m[22m[49m: Microsoft.Azure.SignalR.ServiceConnection[16]
  2020-08-28T15:45:28.412133989Z       Received 3 bytes from service 41b708d2-ae18-497a-9be1-69f6a59d8b95.
  2020-08-28T15:45:30.688580997Z [41m[30mfail[39m[22m[49m: Microsoft.Azure.SignalR.ServiceConnection[8]
  **2020-08-28T15:45:30.688610597Z       Application task failed.
  2020-08-28T15:45:30.688622296Z Microsoft.Azure.SignalR.Common.AzureSignalRException: Cancelled running application task, probably caused by time out.
  2020-08-28T15:45:30.688625996Z    at Microsoft.Azure.SignalR.ServiceConnection.ProcessIncomingMessageAsync(ClientConnectionContext connection)
  2020-08-28T15:45:30.688629996Z    at Microsoft.Azure.SignalR.ServiceConnection.ProcessClientConnectionAsync(ClientConnectionContext connection)**
  2020-08-28T15:45:30.706294782Z [40m[37mdbug[39m[22m[49m: Microsoft.Azure.SignalR.ServiceConnection[13]
  2020-08-28T15:45:30.706310382Z       Sending close connection message to the service for PoVsEq-Dzmdv8s2L3PFMXw4bfe3b071.

### To Reproduce

Start a single Azure SignalR Service. Allow for multiple app servers, 2, 3 or 4 to connect to ASRS. In our case we are using Kubernetes with ingress and have 2 Pod instances per blue/green cluster, so 4 instances connect to ASRS (20 connections). We also at startup of each instance set the .ApplicationName = Environment.MachineName.Replace("-", ""); as part of the AddAzureSignalR options so that as suggested here: https://github.com/Azure/azure-signalr/issues/825. (This is the Pod name from Kubernetes without the "-")

We can then as part of test use any client by starting a client and then killing the client process.  The below exception occurs randomly every so often (It is not always easy to replicate).  **When this happens NO OnDisconnect is fired, therefore, we are unable to rely on the disconnects event and is causing us concern.  We are expecting to move towards 10 - 15K clients and it is business critical for us to ensure the connect and disconnect events are reliable.**

### Exceptions (if any)

  2020-08-28T15:45:30.688580997Z [41m[30mfail[39m[22m[49m: Microsoft.Azure.SignalR.ServiceConnection[8]
  **2020-08-28T15:45:30.688610597Z       Application task failed.
  2020-08-28T15:45:30.688622296Z Microsoft.Azure.SignalR.Common.AzureSignalRException: Cancelled running application task, probably caused by time out.
  2020-08-28T15:45:30.688625996Z    at Microsoft.Azure.SignalR.ServiceConnection.ProcessIncomingMessageAsync(ClientConnectionContext connection)
  2020-08-28T15:45:30.688629996Z    at Microsoft.Azure.SignalR.ServiceConnection.ProcessClientConnectionAsync(ClientConnectionContext connection)**

### Further technical details
- Azure SignalR SDK version 1.5
- ASPNETCORE version 3.1
- Any SignalR Client

**Comment by vicancy** [comment]
The latest version 1.5.1 fixed this issue through #986

**Comment by vicancy** [comment]
About your scenario, so you have 2 clusters, and every cluster has 2 pods.

 Is it that every cluster has the same ApplicationName, or every Pod has a different ApplicationName? 

Please be aware that then clients connected to one app server can not talk to clients connected to another app server with a different ApplicationName because they are considered **different** Applications with different ApplicationName defined.

**Comment by digitalkirkley** [comment]
Great news on the 1.5.1 release and the fix under #986 You couldn't have timed this release any better for us, thank you.  I will continue with our tests for the next 2 - 3 days.  Some early tests seem to indicate we are not seeing the issue.

Also, thank you for the note on the ApplicationName as we didn't realise this. I guess it would have been something we may have seen as we started to scale out and progress our tests further around sending messages.  Really appreciate this. For our scenario we will therefore will NOT be setting the ApplicationName and ensuring each cluster only has 1 Pod (App server) therefore 2 in total.  We will probably begin looking at/introducing the failover primary/secondary configuration at some point soon as we move towards production.

Once again, your help has been greatly appreciated.

**Comment by vicancy** [comment]
Thanks for the updates. I am closing the issue, please feel free to reopen it if you still have concerns about it.
