### ISSUE TITLE
System.IO.InvalidDataException: Expected a hanshake response from the server

### ISSUE THREAD

**Issue by wanlwanl** [Azure/azure-signalr#1200]
### Describe the bug
Got `System.IO.InvalidDataException: Expected a hanshake response from the server` from client. Fail to start connection.

### To Reproduce

send message to the connection itself in `OnConnectionAsync` in my Hub.

### Exceptions (if any)

2021-02-03 14:23:46.902 +00:00 [ERR] Received an invalid handshake response.
System.IO.InvalidDataException: Expected a handshake response from the server.
   at Microsoft.AspNetCore.SignalR.Protocol.HandshakeProtocol.TryParseResponseMessage(ReadOnlySequence`1& buffer, HandshakeResponseMessage& responseMessage)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.HandshakeAsync(ConnectionState startingConnectionState, CancellationToken cancellationToken)
2021-02-03 14:23:46.932 +00:00 [ERR] Error starting connection.
System.IO.InvalidDataException: Expected a handshake response from the server.
   at Microsoft.AspNetCore.SignalR.Protocol.HandshakeProtocol.TryParseResponseMessage(ReadOnlySequence`1& buffer, HandshakeResponseMessage& responseMessage)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.HandshakeAsync(ConnectionState startingConnectionState, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
2021-02-03 14:23:46.955 +00:00 [ERR] Fail to start connection: System.IO.InvalidDataException: Expected a handshake response from the server.
   at Microsoft.AspNetCore.SignalR.Protocol.HandshakeProtocol.TryParseResponseMessage(ReadOnlySequence`1& buffer, HandshakeResponseMessage& responseMessage)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.HandshakeAsync(ConnectionState startingConnectionState, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)

### Further technical details
- Your Azure SignalR SDK version: 1.7.0
- Your Server ASPNETCORE version or Assembly version of `Microsoft.AspNetCore.SignalR` : 3.0
- Your SignalR Client SDK version: 3.0.0

**Comment by wanlwanl** [comment]
fix in #1199

**Comment by vicancy** [comment]
Fixed in v1.7.1
