### ISSUE TITLE
Microsoft.Azure.SignalR.Management 1.7.0 constantly tries to establish socket connection to SignalR service

### ISSUE THREAD

**Issue by mmulhearn** [Azure/azure-signalr#1206]
### Describe the bug
With logging level "Debug" turned on, something in the Management nuget will continuously attempt to establish a socket connection to the signalR service despite being used as "serverless signalr."

As "serverless signalr" is being used, it is not expected that the function would attempt to establish a web socket connection.

This does not occur in `Microsoft.Azure.SignalR.Management 1.6.1`.

### To Reproduce
https://github.com/mmulhearn/azure-sigr-management-issue

Instructions are found in the `readme.md`

### Exceptions (if any)
```
[2021-02-08T14:56:28.537Z] Starting transport. Transfer mode: Binary. Url: 'ws://localhost:8888/server/?hub=signalrfunc&cid=4338c52f-ecd0-4bc8-9e57-7b9b7b8da69f'.
[2021-02-08T14:56:28.540Z] Transport is stopping.
[2021-02-08T14:56:28.541Z] Failed to connect to '(Primary)http://localhost:8888', will retry after the back off period. Error detail: The server returned status code '404' 
when status code '101' was expected.. The server returned status code '404' when status code '101' was expected.. Id: 4338c52f-ecd0-4bc8-9e57-7b9b7b8da69f
```

### Further technical details
- Core Tools Version:       3.0.3233 Commit hash: d1772f733802122a326fa696dd4c086292ec0171 
- Function Runtime Version: 3.0.15193.0

**Comment by brechtvhb** [comment]
Since upgrading to 1.7.0 I am getting the same problem.
Except that i get a 403 exception (about half of the time), whilst my credentials are correct. I am running Azure SignalR in default mode.

[2021-02-08 16:18:42Z ERR] Failed to connect to '(Primary)***', will retry after the back off period. Error detail: The server returned status code '403' when status code '101' was expected.. The server returned status code '403' when status code '101' was expected.. Id: aef8cff3-9355-4bd9-9b09-9f17cd36a17b
[2021-02-08 16:18:42Z INF] Starting transport. Transfer mode: Binary. Url: 'wss://***'.
[2021-02-08 16:18:42Z INF] Transport is stopping.

**Comment by brechtvhb** [comment]
I keep getting 403 exceptions about half of the time, even though the credentials match with the info in the azure portal.
It happens on the server and in the service that sends messages throug the management SDK.

Here's the server errror:
[25/02 13:27:51 - ERR]Failed to connect to '"(Primary)https://xxxx.service.signalr.net"', will retry after the back off period. Error detail: "The server returned status code '403' when status code '101' was expected.. The server returned status code '403' when status code '101' was expected.". Id: "758bd2b9-6d97-434b-9a65-f75f9cc974e1"

Here's the error when using the management SDK.
[2021-02-25 13:04:42Z WRN] Could not send NominationUpdated to SignalR hub.
Microsoft.Azure.SignalR.Common.AzureSignalRRuntimeException: Azure SignalR service runtime error. Request Uri: https://xxx.service.signalr.net/api/v1/hubs/xxx
---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden)
--- End of inner exception stack trace ---
at Microsoft.Azure.SignalR.RestClient.ThrowExceptionOnResponseFailureAsync(HttpResponseMessage response)
at Microsoft.Azure.SignalR.RestClient.SendAsync(RestApiEndpoint api, HttpMethod httpMethod, String productInfo, String methodName, Object[] args, Func`2 handleExpectedResponseAsync, CancellationToken cancellationToken)
at Microsoft.Azure.SignalR.Management.RestHubLifetimeManager.SendAllAsync(String methodName, Object[] args, CancellationToken cancellationToken)

It has been working flawlessly for about 6 months, since february the azure signalR service is unstable for us.

**Comment by Y-Sindo** [comment]
@brechtvhb This seems like a different problem with the original one. Please open a new issue. 

Are you using multiple endpoints with aad? We have detected a bug that multiple endpoints with AAD would fail to authenticate. The bug is fixed in the latest SDK.

What's your SDK version? Can the problem reproduce with the latest SDK?

**Comment by ryanheath** [comment]
@brechtvhb Did you resolve your problem back then? We seem to see the same behaviour, but it is not always returning a 403 ...

// Ryan

**Comment by Y-Sindo** [comment]
@ryanheath Could you please open a new issue to provide more details such as a reproducible project, the error messages?

**Comment by ryanheath** [comment]
@Y-Sindo I created a new issue here #1944 

Thanks!
