### ISSUE TITLE
Ack-able message Microsoft.Azure.SignalR.Protocol.JoinGroupWithAckMessage waiting for ack timed out.

### ISSUE THREAD

**Issue by brechtvhb** [Azure/azure-signalr#1225]
### Describe the bug
when adding a user to a group I get this error:

[2021-02-22 08:37:04Z WRN] Failed to send message null.
System.TimeoutException: Ack-able message Microsoft.Azure.SignalR.Protocol.JoinGroupWithAckMessage waiting for ack timed out.
at Microsoft.Azure.SignalR.ServiceConnectionContainerBase.WriteAckableMessageAsync(ServiceMessage serviceMessage, CancellationToken cancellationToken)
at Microsoft.Azure.SignalR.MultiEndpointMessageWriter.<>c__DisplayClass8_0.<<WriteAckableMessageAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at Microsoft.Azure.SignalR.MultiEndpointMessageWriter.<>c__DisplayClass9_0.<<WriteMultiEndpointMessageAsync>b__2>d.MoveNext()
--- End of stack trace from previous location ---
at Microsoft.Azure.SignalR.MultiEndpointMessageWriter.WriteAckableMessageAsync(ServiceMessage serviceMessage, CancellationToken cancellationToken)
at Microsoft.Azure.SignalR.ServiceLifetimeManagerBase`1.WriteCoreAsync[T](T message, Func`2 task)

### To Reproduce
 call await Groups.AddToGroupAsync(Context.ConnectionId, "groupid", Context.ConnectionAborted); in OnConnectedAsync() in a hub. Occurs most of the time, but not always. Happens even with barely any server load.

### Further technical details
Microsoft.Azure.SignalR 1.7.1 in .NET 5 (linux docker container)

**Comment by brechtvhb** [comment]
Any progress on this? Still having this issue with version 1.8.0.

Let me know if you would need more info.

**Comment by robertlyson** [comment]
Happening to me as well. Don't have reproduction but it's showing up from time to time in our logs.
.Net 5 with Microsoft.Azure.SignalR 1.12.0 installed. 
We are running Azure SignalR standard with 1 unit.

**Comment by rla-resengo** [comment]
Had the same issue, see #754 
Issue was fixed by updating Microsoft.Azure.SignalR to 1.13.0

**Comment by vicancy** [comment]
Please try 1.13.0..
