### ISSUE TITLE
AddToGroupAsync method throws an exception if transport type is transient

### ISSUE THREAD

**Issue by ilya-git** [Azure/azure-signalr#1335]
### Describe the bug

I use latest version of Microsoft.Azure.SignalR.Management to connect to Azure SignalR service.

I first create a hub context with transient transport type and then call this:

`hubContext.Groups.AddToGroupAsync(connectionId, groupName)`

The result is this error:

> Unable to access SignalR service. Response status code does not indicate success: 404 (Not Found) Please make sure the endpoint or DNS setting is correct. Request Uri: https://{service-name}.service.signalr.net/api/v1/hubs/test/groups/aa/connections/{connectionid})

If I use persistent transport type the error does not happen

### Exceptions (if any)

Unhandled exception. System.AggregateException: One or more errors occurred. (Unable to access SignalR service. Response status code does not indicate success: 404 (Not Found) Please make sure the endpoint or DNS setting is correct. Request Uri: {url here})
 ---> Microsoft.Azure.SignalR.Common.AzureSignalRInaccessibleEndpointException: Unable to access SignalR service. Response status code does not indicate success: 404 (Not Found) Please make sure the endpoint or DNS setting is correct. Request Uri: {url here}
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.SignalR.RestClient.ThrowExceptionOnResponseFailureAsync(HttpResponseMessage response)
   at Microsoft.Azure.SignalR.RestClient.SendAsync(RestApiEndpoint api, HttpMethod httpMethod, String productInfo, String methodName, Object[] args, Func`2 handleExpectedResponseAsync, CancellationToken cancellationToken)
   at Microsoft.Azure.SignalR.Management.RestHubLifetimeManager.AddToGroupAsync(String connectionId, String groupName, CancellationToken cancellationToken)
   at SignalRManager.TestPublisher.Program.StartAsync(MessagePublisher publisher) in C:\Source\Scale\uniteaq-signalr-manager-api\SignalRManager.TestPublisher\Program.cs:line 96
   at SignalRManager.TestPublisher.Program.StartAsync(MessagePublisher publisher) in C:\Source\Scale\uniteaq-signalr-manager-api\SignalRManager.TestPublisher\Program.cs:line 115
   at SignalRManager.TestPublisher.Program.<>c__DisplayClass0_0.<<Main>b__0>d.MoveNext() in C:\Source\Scale\uniteaq-signalr-manager-api\SignalRManager.TestPublisher\Program.cs:line 55
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass79_0.<OnExecute>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at SignalRManager.TestPublisher.Program.Main(String[] args) in C:\Source\Scale\uniteaq-signalr-manager-api\SignalRManager.TestPublisher\Program.cs:line 60

### Further technical details
- Your Azure SignalR Management version 1.9.0

**Comment by ilya-git** [comment]
It seems I have messed something up and it works if the connection id exists
