### ISSUE TITLE
Does IsServiceHealthy work?

### ISSUE THREAD

**Issue by jassent** [Azure/azure-signalr#1428]
This [page](https://github.com/Azure/azure-signalr/blob/dev/docs/management-sdk-guide.md#create-service-hub-context) shows the features in Microsoft.Azure.Signalr.Management

This is using Azure Signalr Service in serverless mode and the code is running in an Azure Function using .Net 5.0

```
var serviceManager = new ServiceManagerBuilder()
                    .WithOptions(option =>
                    {
                        option.ConnectionString = Environment.GetEnvironmentVariable("Azure__SignalR__ConnectionString");
                    })                                        
                    .BuildServiceManager();

var h = await serviceManager.IsServiceHealthy(default);
```

Other calls into the service manager seem to work:

`var x = await serviceHubContext.ClientManager.ConnectionExistsAsync("test@test.com");`

 IsServiceHealthy produces an error which is below.

Does this method really work or is it not to be used in serverless mode?

```
[2021-09-03T17:41:45.727Z] Executed 'Functions.SignalRManagement' (Failed, Id=dbeca876-b029-4392-b524-9ab648270a37, Duration=961ms)
[2021-09-03T17:41:45.730Z] System.Private.CoreLib: Exception while executing function: Functions.SignalRManagement. System.Private.CoreLib: Result: Failure
Exception: System.AggregateException: One or more errors occurred. (A task was canceled.)
[2021-09-03T17:41:45.733Z]  ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
[2021-09-03T17:41:45.735Z]    at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
[2021-09-03T17:41:45.738Z]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[2021-09-03T17:41:45.740Z]    at System.Threading.Tasks.Task`1.get_Result()
[2021-09-03T17:41:45.744Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
[2021-09-03T17:41:45.747Z]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[2021-09-03T17:41:45.752Z]    at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
[2021-09-03T17:41:45.755Z]    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
[2021-09-03T17:41:45.757Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[2021-09-03T17:41:45.760Z]    at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
[2021-09-03T17:41:45.764Z]    at System.Threading.Tasks.Task.ExecuteFromThreadPool(Thread threadPoolThread)
[2021-09-03T17:41:45.768Z]    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[2021-09-03T17:41:45.770Z]    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
[2021-09-03T17:41:45.773Z] --- End of stack trace from previous location ---
[2021-09-03T17:41:45.775Z]
[2021-09-03T17:41:45.777Z]    --- End of inner exception stack trace ---
[2021-09-03T17:41:45.782Z]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[2021-09-03T17:41:45.785Z]    at System.Threading.Tasks.Task`1.get_Result()
[2021-09-03T17:41:45.787Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
[2021-09-03T17:41:45.790Z]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[2021-09-03T17:41:45.792Z]    at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
[2021-09-03T17:41:45.795Z]    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
[2021-09-03T17:41:45.801Z] --- End of stack trace from previous location ---
[2021-09-03T17:41:45.803Z]    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
[2021-09-03T17:41:45.806Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[2021-09-03T17:41:45.808Z] --- End of stack trace from previous location ---
[2021-09-03T17:41:45.811Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 44
[2021-09-03T17:41:45.816Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2021-09-03T17:41:45.819Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 166
Stack:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[2021-09-03T17:41:45.822Z]    at System.Threading.Tasks.Task`1.get_Result()
[2021-09-03T17:41:45.825Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
[2021-09-03T17:41:45.831Z]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[2021-09-03T17:41:45.833Z]    at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
[2021-09-03T17:41:45.836Z]    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
[2021-09-03T17:41:45.838Z] --- End of stack trace from previous location ---
[2021-09-03T17:41:45.841Z]    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
[2021-09-03T17:41:45.846Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[2021-09-03T17:41:45.849Z] --- End of stack trace from previous location ---
[2021-09-03T17:41:45.851Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 44
[2021-09-03T17:41:45.854Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2021-09-03T17:41:45.857Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 166.
```

**Comment by Y-Sindo** [comment]
`IsServiceHealthy` can be used in any mode. There is a bug and will be fixed in next release.
