### ISSUE TITLE
Client connections can not be open during the sequential integration tests run

### ISSUE THREAD

**Issue by amnezin** [Azure/azure-signalr#1513]
Hello,
Faced an issue during playing with the SignalR:
When I run a single test multiple times manually, every time it passes
![image](https://user-images.githubusercontent.com/18722254/147119085-ee76ee2a-4db6-4a25-a946-a6f37776e49d.png)
But when I added the second (third etc) test, the client connection opening fails (randomly first and second) with the System.OperationCanceledException.
```
System.OperationCanceledException
The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.HandshakeAsync(ConnectionState startingConnectionState, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
   at signalr_management_test.SignalRManagementTests.SignalRTest(String signalRHubName) in signalr-management-test\signalr-management-test\SignalRManagementTests.cs:line 77
```

![image](https://user-images.githubusercontent.com/18722254/147120170-765f5c6a-b13e-4a05-a38a-bd971343d8e0.png)
I even faced the situation when the only third test failed on trying to open a second client connection
![image](https://user-images.githubusercontent.com/18722254/147119940-1c6cb3fd-0768-4ef6-9f6b-4e4a70a23196.png)

The repository where the issue can be easily reproduced: https://github.com/amnezin/signalr-management-test

I use the following NuGet packages:
Microsoft.AspNetCore.SignalR.Client 5.0.12
Microsoft.Azure.SignalR 1.13.0
Microsoft.Azure.SignalR.Management 1.13.0
Microsoft.AspNetCore.Mvc.Testing 3.1.21
Microsoft.NET.Test.Sdk 17.0.0
xunit 2.4.1
xunit.runner.console 2.4.1
xunit.runner.visualstudio 2.4.3

Thanks!

**Comment by Y-Sindo** [comment]
I reproduced your issues. The first test always passes, while the later tests are likely to fail. The reason is that during the client connection handshaking with service, the SignalR service routes the client connection to a non-existent server-service connection created in the last unit tests due to route table update latency, which causes the handshake timeout. Recommend you to use class fixture to hold the test server, so that it is not created for each unit test.

**Comment by amnezin** [comment]
Thanks for the advice!

**Comment by CodeOutput** [comment]
![Image](https://github.com/user-attachments/assets/5740c63d-e3b4-41cc-88da-64ad39042625)
