### ISSUE TITLE
Running Azure SignalR Emulator in docker

### ISSUE THREAD

**Issue by Arash-Sabet** [Azure/azure-signalr#1559]
### Is your feature request related to a problem? Please describe.
We have an application working in docker but it relies on an instance of an Azure SignalR Service hosted on cloud. Due to some business reasons, we want each instance of the docker image to use a segregated version of signalR service. Therefore, we want to embed the SignalR Emulator in it.

### Describe the solution you'd like
I'd like to see an example of setting up this emulator in docker.

**Comment by vicancy** [comment]
May I ask the reason for not using self-host SignalR?

**Comment by vicancy** [comment]
> the self-hosted signalR broadcasts disconnection event 

Could you illustrate this more? I think the disconnection event is triggered by one Hub server only.

**Comment by Arash-Sabet** [comment]
> > the self-hosted signalR broadcasts disconnection event
> 
> Could you illustrate this more? I think the disconnection event is triggered by one Hub server only.

The disconnection event will be caught and handled by all instances of the signalR client applications. We share docker images among developers which contains all tiers of our application (e.g. Azure Functions, ASP.NET app, etc.). Putting a SignalR emulator instance in our docker image rather than creating multiple services on Azure helps us have a more abstract environment.

**Comment by vicancy** [comment]
> The disconnection event will be caught and handled by all instances of the signalR client applications
Do you mean "disconnection" event for a SignalR client? one SignalR client disconnect triggers one "disconnection" event for this particular client. 

Emulator is designed for easy local debug for the transient serverless scenario, I am a little concerned about the design limitation and code quality of the Emulator to meet the PROD usage bar. Anyway you can always install the Emulator using `dotnet tool install  -g Microsoft.Azure.SignalR.Emulator --version 1.0.0-preview1-10809` as the same way you install any other dotnet tools in docker if you like.

**Comment by Arash-Sabet** [comment]
> Do you mean "disconnection" event for a SignalR client? 

Yes

**Comment by vicancy** [comment]
Why "disconnection" event for one SignalR client will be handled by **all** instances?

**Comment by vicancy** [comment]
Please feel free to reopen the issue if there are any updates.

**Comment by oadrian2** [comment]
It would be nice to have the emulator work with docker for the purpose of docker compose (e.g., cosmos db, azurite) and for use with Azure Functions which may not be dotnet.

**Comment by MuhammadMustafa-IS** [comment]
@vicancy  It works outside docker, but I tried to get it to work in docker but it won't work, I keep getting connection refused 

This is the Dockerfile I have 
```yml
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR emulator

RUN dotnet tool install -g Microsoft.Azure.SignalR.Emulator

COPY . .

ENV PATH="/root/.dotnet/tools:${PATH}"

ENTRYPOINT ["asrs-emulator", "start"]
```

docker-compose.yml
```yml
services:
  signalr-emulator:
    container_name: signalr-emulator
    build: 
      context: ./
      dockerfile: Dockerfile
    image: signalr-emulator
    ports:
      - "7071:7071"
      - "8888:8888"
  resource:
    container_name: resource-service
    build: 
      context: ../../ResourceService/ResourceService.Controllers
      dockerfile: dockerfile
    image: resource-service-controllers
    ports:
      - 7000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=local
    depends_on:
      - signalr-emulator     
```

![image](https://github.com/user-attachments/assets/db4868d6-57da-445f-94e1-65f8cde72492)

I'm using this connection string: 
```json
"ConnectionString": "Endpoint=http://signalr-emulator;Port=8888;AccessKey=ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGH;Version=1.0;"
```

I keep getting this error 

```log
2024-07-22 10:17:40       Unhandled exception caught.
2024-07-22 10:17:40       Microsoft.Azure.SignalR.Common.AzureSignalRException: An error happened when making request to http://signalr-emulator:8888/api/hubs/t%5B22bc17f1_7700_469d_b000_6cf0c91f4e45%5Dresources/users/226e905c-00cb-4384-817c-7ab5805cfd2b/groups/test?api-version=2022-06-01
2024-07-22 10:17:40        ---> System.Net.Http.HttpRequestException: Connection refused (signalr-emulator:8888)
2024-07-22 10:17:40        ---> System.Net.Sockets.SocketException (111): Connection refused
2024-07-22 10:17:40          at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
2024-07-22 10:17:40          at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
2024-07-22 10:17:40          at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
2024-07-22 10:17:40          at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
2024-07-22 10:17:40          --- End of inner exception stack trace ---
2024-07-22 10:17:40          at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
2024-07-22 10:17:40          at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2024-07-22 10:17:40          at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2024-07-22 10:17:40          at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
2024-07-22 10:17:40          at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
2024-07-22 10:17:40          at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
2024-07-22 10:17:40          at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2024-07-22 10:17:40          at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2024-07-22 10:17:40          at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
2024-07-22 10:17:40          at Microsoft.Azure.SignalR.Management.TimeoutHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2024-07-22 10:17:40          at Microsoft.Azure.SignalR.Management.RetryHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2024-07-22 10:17:40          at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
2024-07-22 10:17:40          at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
2024-07-22 10:17:40          at Microsoft.Azure.SignalR.RestClient.SendAsyncCore(String httpClientName, RestApiEndpoint api, HttpMethod httpMethod, String methodName, Object[] args, Func`2 handleExpectedResponseAsync, CancellationToken cancellationToken)
2024-07-22 10:17:40          --- End of inner exception stack trace ---
2024-07-22 10:17:40          at Microsoft.Azure.SignalR.RestClient.SendAsyncCore(String httpClientName, RestApiEndpoint api, HttpMethod httpMethod, String methodName, Object[] args, Func`2 handleExpectedResponseAsync, CancellationToken cancellationToken)
2024-07-22 10:17:40          at Microsoft.Azure.SignalR.Management.RestHubLifetimeManager`1.UserAddToGroupAsync(String userId, String groupName, CancellationToken cancellationToken)
2024-07-22 10:17:40          at ResourceService.Providers.Providers.SignalRNegotiationProvider.Negotiate(String channel, String[] groupNames, CancellationToken token) in C:\Home\MiView\MiPlatform\apps\ResourceService\ResourceService.Providers\Providers\SignalRNegotiationProvider.cs:line 37
2024-07-22 10:17:40          at ResourceService.Controllers.NegotiateController.Negotiate(NegotationRequest request, CancellationToken token) in C:\Home\MiView\MiPlatform\apps\ResourceService\ResourceService.Controllers\Controllers\NegotiateController.cs:line 31
2024-07-22 10:17:40          at lambda_method9(Closure, Object)
2024-07-22 10:17:40          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
2024-07-22 10:17:40          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
2024-07-22 10:17:40          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-07-22 10:17:40          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
2024-07-22 10:17:40          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2024-07-22 10:17:40          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-07-22 10:17:40          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-07-22 10:17:40          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
2024-07-22 10:17:40          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2024-07-22 10:17:40          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-07-22 10:17:40          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
2024-07-22 10:17:40          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
```

**Comment by cqnguy23** [comment]
Hi @MuhammadMustafa-IS, could you please apply these two changes to your current configuration:
1. For the connection string, change to `Endpoint=http://localhost;Port=8888;AccessKey=ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGH;Version=1.0;`. This is essentially because you're trying to establish the connection from your browser, not the service container, so using the container name as the host wouldn't work here.
2. In the emulator Dockerfile, change the ENTRYPOINT to `["asrs-emulator", "start", "-i", "0.0.0.0"]`. This is to bind the Emulator application to all available network interfaces within the container, not just only the loopback interface (which would be inaccessible outside the container itself)

Please let me know if you still encounter issues after these changes. Thank you

**Comment by MuhammadMustafa-IS** [comment]
> ["asrs-emulator", "start", "-i", "0.0.0.0"]

This ENTRYPOINT made it work thank you. 

I'm using the connection string inside docker compose within other APIs, that's why I'm using the SignalR container name instead of localhost.
