### ISSUE TITLE
Migrating from .NET Core 3.1 > 6.0 Can no longer connect to Hub Endpoint

### ISSUE THREAD

**Issue by rachael-ross** [Azure/azure-signalr#1648]
### Describe the bug
We've recently migrated from .NET Core 3.1 to .NET 6.0.5 on our web-based api. Our client SPA web app and our console test app can no longer connect to the configured endpoint within the api. I can't seem to figure out what's changed in how to configure the hub endpoint. All mentions of deprecated methods I've confirmed we're not using.

### To Reproduce

The configuration we've successfully used for months using .NET Core 3.1:

```
  services.AddAuthentication(options =>
                {
                    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
                })
                .AddJwtBearer("B2C1", options =>
                {
                    options.Authority = Configuration["AzureAdB2C:Authority1"];

                    options.Events = new JwtBearerEvents
                    {
                        OnMessageReceived = context =>
                        {
                            var accessToken = context.Request.Query["access_token"];

                            // If the request is for our SignalR hub - MS sends the auth token in the querystring over websocket
                            var path = context.HttpContext.Request.Path;
                            if (!string.IsNullOrEmpty(accessToken) &&
                                (path.StartsWithSegments("/notifhub")))
                            {
                                // Read the token out of the query string
                                context.Token = accessToken;
                            }
                            return Task.CompletedTask;
                        }
                    };
};

services.AddSignalR().AddAzureSignalR();  // where services is IServiceCollection

. . .
 app.UseHttpsRedirection();

            app.UseStaticFiles();          
            app.UseCors("corspolicy");
            app.UseRouting();            
            app.UseAuthentication();
            app.UseAuthorization();

            // for SignalR Hub
            app.UseFileServer();

            app.UseJsonApi();   
            
            app.UseEndpoints(endpoints =>
            {
                // SignalR Hub
                endpoints.MapHub<NotificationHub>("/notifhub");
                endpoints.MapControllers();
                endpoints.MapSwagger("swagger/{documentName}/swagger.json");
            });           
```

### Exceptions (if any)
 The SPA client is receiving a CORS error, while a 404 is being logged by the api in Application Insights.
I have a console app to test locally and am receiving:

500 Error

**StackTrace:**

 ```
  at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<NegotiateAsync>d__45.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<GetNegotiationResponseAsync>d__52.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<SelectAndStartTransport>d__44.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<StartAsyncCore>d__41.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<StartAsync>d__40.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.<ConnectAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.<ConnectAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsyncCore>d__58.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsyncInner>d__50.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsync>d__49.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at NotificationHub.TestClient.Program.Main(String[] args) in C:\SourceCode\Repos\xxxapi\NotificationHub.TestClient\Program.cs:line 44

```
**SerializationStackTrace:**

 ```
  at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.GetNegotiationResponseAsync(Uri uri, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
   at NotificationHub.TestClient.Program.Main(String[] args) in C:\SourceCode\Repos\xxxapi\NotificationHub.TestClient\Program.cs:line 44
```
```
gdbug: Microsoft.AspNetCore.SignalR.Client.HubConnection[40]
      Registering handler for client method 'NewNotification'.
trce: Microsoft.AspNetCore.SignalR.Client.HubConnection[42]
      Waiting on Connection Lock in StartAsyncInner (/_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:247).
trce: Microsoft.AspNetCore.SignalR.Client.HubConnection[80]
      The HubConnection is attempting to transition from the Disconnected state to the Connecting state.
dbug: Microsoft.AspNetCore.SignalR.Client.HubConnection[41]
      Starting HubConnection.
dbug: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[1]
      Starting HttpConnection.
dbug: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[8]
      Establishing connection with server at 'https://localhost:44301/notifhub'.
trce: Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler[1]
      Sending HTTP request POST 'https://localhost:44301/notifhub/negotiate?negotiateVersion=1'.
warn: Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler[2]
      Unsuccessful HTTP response 500 return from POST 'https://localhost:44301/notifhub/negotiate?negotiateVersion=1'.
fail: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[10]
      Failed to start connection. Error getting negotiation response from 'https://localhost:44301/notifhub'.
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger, CancellationToken cancellationToken)
dbug: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[5]
      Skipping dispose, connection is already disposed.
trce: Microsoft.AspNetCore.SignalR.Client.HubConnection[80]
      The HubConnection is attempting to transition from the Connecting state to the Disconnected state.
trce: Microsoft.AspNetCore.SignalR.Client.HubConnection[20]
      Releasing Connection Lock in StartAsyncInner (/_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:280).
```
### Further technical details
- Your Azure SignalR SDK version: just updated to 1.18.1 (was using 1.17 when it was working)
- Your Server ASPNETCORE version or Assembly version of `Microsoft.AspNetCore.SignalR` : Both 6.0.7
- Your SignalR Client SDK version: 6.0.7 (for the test console app) - 6.0.2 (for Web App)

**Comment by JialinXin** [comment]
Hi @rachael-ross , thanks for reporting the issue!

There's no breaking change in server SDK on Net6.0. I did a test following your shared code snippet except for the `app.UseCors("corspolicy");` as I don't know your cors policy. It looks everything is working well. Would you share more context behind your scenario? Or a mini repo project that repro your issue is welcomed. It would help us easier investigate your case.

**Comment by rachael-ross** [comment]
Sure, I'll work on that. Thank you, @JialinXin

**Comment by vicancy** [comment]
Please feel free to reopen the issue if there are updates.
