### ISSUE TITLE
 Connection 979e5f03-b7d5-4c21-9776-c94baf463e7b to the service was dropped.

### ISSUE THREAD

**Issue by gynet** [Azure/azure-signalr#166]
fail: Microsoft.Azure.SignalR.ServiceConnection[4]
      Connection 979e5f03-b7d5-4c21-9776-c94baf463e7b to the service was dropped.
System.Net.Http.WinHttpException (0x80072EE2): The operation timed out
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.WebSockets.WinHttpWebSocket.<ReceiveAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.<StartReceiving>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.Azure.SignalR.ServiceConnection.<ProcessIncomingAsync>d__34.MoveNext()
fail: Microsoft.Azure.SignalR.ServiceConnection[1]
      Failed to send message to the service.

**Comment by vicancy** [comment]
Hi @gynet, when did you experience this error? Is it happening all the time or just occasionally? Did messages get lost within that period?

This error can happen due to network issues, and SignalR SDK handles such case with auto-reconnet logic.

**Comment by gynet** [comment]
It happened occasionally this morning, and now it just has gone.

**Comment by xscript** [comment]
It looks like a network issue. Does it happen again? Can we close this issue?

**Comment by gynet** [comment]
@xscript  it's gone. It does not happen again, I think we can close this issue
