### ISSUE TITLE
Microsoft.Azure.SignalR.Common.AzureSignalRException: Ack-able message Microsoft.Azure.SignalR.Protocol.JoinGroupWithAckMessage gets error ack status 4

### ISSUE THREAD

**Issue by SergeyOsipenko** [Azure/azure-signalr#1660]
### Describe the bug
When adding a user to several groups I get this error:

System.AggregateException: One or more errors occurred. (Ack-able message Microsoft.Azure.SignalR.Protocol.JoinGroupWithAckMessage gets error ack status 4.)
 ---> Microsoft.Azure.SignalR.Common.AzureSignalRException: Ack-able message Microsoft.Azure.SignalR.Protocol.JoinGroupWithAckMessage **gets error ack status 4**.
   at Microsoft.Azure.SignalR.ServiceConnectionContainerBase.WriteAckableMessageAsync(ServiceMessage serviceMessage, CancellationToken cancellationToken)
   at Microsoft.Azure.SignalR.MultiEndpointMessageWriter.<>c__DisplayClass10_0.<b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.SignalR.MultiEndpointMessageWriter.WriteSingleEndpointMessageAsync(HubServiceEndpoint endpoint, ServiceMessage serviceMessage, Func`2 inner)
   at Microsoft.Azure.SignalR.MultiEndpointMessageWriter.WriteMultiEndpointMessageAsync(ServiceMessage serviceMessage, Func`2 inner)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.SignalR.MultiEndpointMessageWriter.WriteMultiEndpointMessageAsync(ServiceMessage serviceMessage, Func`2 inner)
   at Microsoft.Azure.SignalR.MultiEndpointMessageWriter.WriteSingleResultAckableMessage(ServiceMessage serviceMessage, CancellationToken cancellationToken)
   at Microsoft.Azure.SignalR.ServiceLifetimeManagerBase`1.WriteAckableCoreAsync[T](T message, Func`2 task)

### To Reproduce

call AddToGroupAsync several times for the user

```
foreach(string roomId in roomIDs)
{
     await Groups.AddToGroupAsync(Context.ConnectionId, roomId ); 
}
```
It happens time to time and with any server load

### Further technical details
- Microsoft.Azure.SignalR 1.18.1
- .Net 6
- No SDK version for client. Pure WebSocket protocol is used to get access to the server and send messages\events

**Comment by SergeyOsipenko** [comment]
I also found a place where it comes from:

https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-signalr%2Fblob%2Fdev%2Fsrc%2FMicrosoft.Azure.SignalR.Common%2FServiceConnections%2FServiceConnectionContainerBase.cs&data=05%7C01%7Cs_asipenka%40goodyear.com%7Cb29c4403418245c75fa608da811b1a71%7C939e896692854a9a9f040887efe8aae0%7C0%7C0%7C637964250696628559%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fL0mvtep7BP18t7v5vfWKygHgNU%2Fd9%2FnjzrMYUy1pI0%3D&reserved=0

![image](https://user-images.githubusercontent.com/22179497/185578352-cde0a0f5-d46a-4a73-896e-e687a0328801.png)

But unfortunately I know nothing about **Status Code 4**

**Comment by vicancy** [comment]
4 is InternalServerError, this looks like SDK bug not covering the status code, should fix.

For the InternalServerError, could you also email me(`lianwei(at)microsoft.com`) your resource name and the timestamp list when the error throws for me to take a further look?
