### ISSUE TITLE
protocol name is case sensitive while aspnet core signalr in insensitive

### ISSUE THREAD

**Issue by wanlwanl** [Azure/azure-signalr#1760]
### Describe the bug
protocol name is case sensitive while aspnet core signalr in insensitive

### To Reproduce

Use a custom json protocol named 'Json' (the only difference to `JsonHubProtocol`)

### Exceptions (if any)
```
ExceptionType: "KeyNotFoundException" -- Message: "The given key 'Json' was not present in the dictionary." -- StackTrace: "   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.Azure.SignalR.ServiceLifetimeManager`1.CreateMessage(String connectionId, String methodName, Object[] args, ClientConnectionContext serviceConnectionContext)
```

### Further technical details
- 1.19.0

**Comment by wanlwanl** [comment]
#1758 
#1759
