### ISSUE TITLE
HeartBeat.StopAsync() sometimes causes TimerAwaitable.Stop() to throw ObjectDisposedException

### ISSUE THREAD

**Issue by sergethedev17** [Azure/azure-signalr#1789]
We use `Microsoft.AspNetCore.Mvc.Testing` library and `xUnit` for testing our ASP NET Core API:
We create a `WebApplicationFactory<TEntryPoint>` to setup a testable API server.
When we dispose an instance of `WebApplicationFactory<TEntryPoint>`, occasionally we see this:
```
  Message: 
System.AggregateException : One or more hosted services failed to stop. (Cannot access a disposed object.
Object name: 'Microsoft.Azure.SignalR.TimerAwaitable'.)
---- System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'Microsoft.Azure.SignalR.TimerAwaitable'.

  Stack Trace: 
Host.StopAsync(CancellationToken cancellationToken)
WebApplicationFactory`1.DisposeAsync()
WebApplicationFactory`1.Dispose(Boolean disposing)
WebApplicationFactory`1.Dispose()
  StartupTestBase.Dispose(Boolean disposing) line 50
StartupTestBase.Dispose() line 59
ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) line 79
----- Inner Stack Trace -----
TimerAwaitable.Stop()
HeartBeat.StopAsync(CancellationToken cancellationToken)
Host.StopAsync(CancellationToken cancellationToken)
```

This behaviour is intermittent.

### To Reproduce

Here is a sample unit test:
```
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace CompanyNamespace.App.Tests
{
    public class WebAppStartupTests : IDisposable
    {
        private bool disposedValue;

        /*
         * 'Program' is the name of the entry-point class for an ASP.NET Core app.
         * See: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/?view=aspnetcore-7.0&tabs=windows#programcs
         */
        internal WebApplicationFactory<Program> Factory { get; }

        public WebAppStartupTests()
        {
            Factory = new WebApplicationFactory<Program>().WithWebHostBuilder(Configure);
        }
        protected void Configure(IWebHostBuilder builder)
        {
            builder.ConfigureServices(collection => collection.AddLogging());
            // More config goes here
        }

        [Theory]
        [InlineData("Production")]
        [InlineData("Staging")]
        [InlineData("IntegrationTests")]
        public void When_specified_environment_startup_should_do_xyz(string environment)
        {
            using var factory = Factory.WithWebHostBuilder(builder => builder.UseEnvironment(environment));

            // Do some tests
        }

        protected virtual void Dispose(bool disposing)
        {
            if (!disposedValue)
            {
                if (disposing)
                {
                    Factory.Dispose();
                }

                disposedValue = true;
            }
        }
        public void Dispose()
        {
            Dispose(disposing: true);
            GC.SuppressFinalize(this);
        }
    }
}
```

### Exceptions (if any)
```
System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'Microsoft.Azure.SignalR.TimerAwaitable'.
```

### Further technical details
- TargetFramework: net7.0
- Microsoft.Azure.SignalR 1.21.3
- Microsoft.AspNetCore.TestHost 6.0.9
- Microsoft.AspNetCore.SignalR.Client 6.0.14
- Microsoft.AspNetCore.Mvc.Testing 6.0.9
- xunit 2.4.2

**Comment by vicancy** [comment]
Thanks for reporting the issue Serge, I am unable to repro the issue, wondering if there are any logic in your Program or test that can trigger the issue. I noticed that you are also using SignalR client `Microsoft.AspNetCore.SignalR.Client`, is this used in your test? Is it possible for you to share with me a minimum repro-able project?

**Comment by ajbeaven** [comment]
I'm experiencing a similar issue but struggled to make a repro project without hackery involved. The closest I got was this:

[SignalrWebApplicationFactoryConflict.zip](https://github.com/Azure/azure-signalr/files/13040343/SignalrWebApplicationFactoryConflict.zip)

Instructions for use:
1. Run nuget package restore
2. Update azure signalr service connection string in appsettings.json to point to a valid instance (not sure if ASRS is a necessary component here)
3. Put a breakpoint in the `TestCleanup()` method in `Test.cs`
4. **Debug** the test, hit the breakpoint and continue

The following exception should be thrown:
```
System.AggregateException: One or more hosted services failed to stop. (Cannot access a disposed object.
Object name: 'Microsoft.Azure.SignalR.TimerAwaitable'.)
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Microsoft.Azure.SignalR.TimerAwaitable'.
   at Microsoft.Azure.SignalR.TimerAwaitable.Stop()
   at Microsoft.Azure.SignalR.HeartBeat.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.WaitForShutdownAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in C:\Users\ajbea\source\repos\SignalrWebApplicationFactoryConflict\SignalrWebApplicationFactoryConflict\Program.cs:line 18
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Note: the exception is not thrown if you disable the breakpoint. I couldn't find a way to reproduce this issue in a minimum repro project without doing this, so hopefully this is enough to investigate.

**Comment by vicancy** [comment]
`HeartBeat.StopAsync` is called twice:
1. `Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory<Program>.Dispose` => `Microsoft.AspNetCore.Mvc.Testing.DeferredHostBuilder.DeferredHost.StopAsync` => `Microsoft.Extensions.Hosting.Internal.Host.StopAsync` =>`HeartBeat.StopAsync`
2. `HostingAbstractionsHostExtensions.RunAsync` => `HostingAbstractionsHostExtensions.WaitForShutdownAsync` => `Microsoft.Extensions.Hosting.Internal.Host.StopAsync` =>`HeartBeat.StopAsync`
