### ISSUE TITLE
Azure SignalR authentication not working for custom Blazor Server Hubs with Azure AD B2C

### ISSUE THREAD

**Issue by njannink** [Azure/azure-signalr#1798]
### Describe the bug
We use Azure AD B2C to authtenticate users in our web portal and use SignalR to send dedicated messages  between user groups based on the rooms you have access too. This is all working fine when I self host SignalR, but on our production server we use Azure SignalR and there the authentication isn't working even though I pass all headers and cookies as described in this article:

https://learn.microsoft.com/en-us/answers/questions/1160923/solution-custom-signalr-endpoints-(hubs)-in-a-blaz

Any idea how I can get authentication to work for custom Blazor Server hubs?

### Exceptions (if any)
```
System.IO.InvalidDataException: Invalid negotiation response received.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at Microsoft.AspNetCore.Internal.SystemTextJsonExtensions.CheckRead(Utf8JsonReader& reader)
   at Microsoft.AspNetCore.Http.Connections.NegotiateProtocol.ParseResponse(ReadOnlySpan`1 content)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Http.Connections.NegotiateProtocol.ParseResponse(ReadOnlySpan`1 content)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.GetNegotiationResponseAsync(Uri uri, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
```

### Further technical details
AspNetCore 7.0.7
Microsoft.Azure.SignalR Version="1.21.4
Microsoft.Identity.Web Version="2.12.4"
Microsoft.AspNetCore.SignalR.Client Version="7.0.7"

**Comment by njannink** [comment]
I found out the issue had to do with the Azure Frontdoor that I was using. This was working fine for Blazor Wasm, but for a statefull Blazor Server app service this doesn't work. so I disabled the frontdoor
