### ISSUE TITLE
NegotiationResponse fails when using authorization

### ISSUE THREAD

**Issue by Roodem** [Azure/azure-signalr#1814]
Hello,
I am developing an android app and I'm attempting to setup signalR to connect to my blazor web app hub. The signalR implementation I'm currently using a signalR service in azure using the default service mode.

I seem to be facing a problem when I'm enabling my authorization on my hub, I've attempted different ways on adding my bearer token when connecting to the hub, but this without any success as I keep getting a negotiation response exception. When I disable my authorization on the hub, things work fine.

In android I've attempted to add a bearer token with the withHeader method and the withAccessTokenProvider on the HubConnectionBuilder, but that didnt work. The java library I'm using for this is ` implementation 'com.microsoft.signalr:signalr:7.0.0'`

Method 1:
```
String token = "<my auth0 bearer token>";

hubConnection = HubConnectionBuilder.create(connectionUrl)
                .withAccessTokenProvider(Single.defer(() -> {
                    return Single.just(token);
                }))
                .build();					
```

Method 2:
	
 ```
 hubConnection = HubConnectionBuilder.create(connectionUrl)
                .withHeader("Authorization", token)
                .build();
```

My hub has the following implementation, I've added the` [Authorize]` attribute on top of my hub.

```
[Authorize]

public sealed class MyHub : Hub<IMyHubCommunicationsHub>

{

    public async Task OutgoingCall(string user, string message)

        => await Clients.All.IncomingCall(user, message);

 

    public async Task HubConnectionChanged(HubConnectionChangedPayload payload)

        => await Clients.All.HubConnectionChanged(payload);

 



    public override async Task OnConnectedAsync()

    {

        var userIdentifier = GetUserIdentifierFromHubCallerContext(Context);

 

        if (Guid.TryParse(userIdentifier, out Guid userId))

        {

            await Groups.AddToGroupAsync(Context.ConnectionId, userId.ToString());

        }

 

        await base.OnConnectedAsync();

    }

 

    public override async Task OnDisconnectedAsync(Exception? exception)

    {

        var userIdentifier = GetUserIdentifierFromHubCallerContext(Context);

 

        if (Guid.TryParse(userIdentifier, out Guid userId))

        {

            await Groups.RemoveFromGroupAsync(Context.ConnectionId, userId.ToString());

        }

 

        await base.OnDisconnectedAsync(exception);

    }

 



    #region Helpers

 

    private static string? GetUserIdentifierFromHubCallerContext(HubCallerContext hubCallerContext)

    {

        if (hubCallerContext.UserIdentifier.IsNotNullOrWhiteSpace())

        {

            if (Guid.TryParse(hubCallerContext.UserIdentifier, out Guid userIdentifier))

            {

                return userIdentifier.ToString();

            }

            else

            {

                return hubCallerContext.UserIdentifier.ToUniqueIdentifier().ToString();

            }

        }

 

        var httpContext = hubCallerContext.GetHttpContext();

 

        if (httpContext.IsNull())

        {

            return null;

        }

 

        if (httpContext.Request.Headers.TryGetValue("X-USER-ID", out StringValues headerValue))

        {

            return headerValue.Equals(Guid.Empty.ToString()) ? null : headerValue.ToString();

        }

 

        if (httpContext.Request.Query.TryGetValue("user", out StringValues queryValue))

        {

            return queryValue.Equals(Guid.Empty.ToString()) ? null : queryValue.ToString();

        }

 

        return null;

    }

 

    #endregion

}
```

Lastly, the middleware im using for my blazor app is this

```
using System.Net;

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.Azure.SignalR;

using myapplication;

#endregion

namespace MyApp.Web.DependencyInjection;

public static partial class IServiceCollectionExtensions
{
    public static IServiceCollection AddAzureSignalR(this IServiceCollection services, ConfigurationManager configurationManager)
    {
        var uri = configurationManager["App:Azure:SignalR:Uri"] ?? throw new InvalidOperationException("Required configuration settting 'Azure.SignalR.Uri' is missing.");

        services.AddServerSideBlazor(options =>
        {
#if DEBUG
            options.DetailedErrors = true;
#else
            options.DetailedErrors = false;
#endif
            options.MaxBufferedUnacknowledgedRenderBatches = 10;
            options.DisconnectedCircuitMaxRetained = 100;
            options.DisconnectedCircuitRetentionPeriod = TimeSpan.FromSeconds(5);
            options.JSInteropDefaultCallTimeout = TimeSpan.FromSeconds(60);
        })
        .AddHubOptions(options =>
        {
#if DEBUG
            options.EnableDetailedErrors = true;
#else
            options.EnableDetailedErrors = false;
#endif
            options.ClientTimeoutInterval = TimeSpan.FromSeconds(30);
            options.HandshakeTimeout = TimeSpan.FromSeconds(15);
            options.KeepAliveInterval = TimeSpan.FromSeconds(15);
            options.MaximumParallelInvocationsPerClient = 1;
            options.MaximumReceiveMessageSize = 32 * 1024;
            options.StreamBufferCapacity = 10;
        });

        services.AddSignalR(options =>
        {
#if DEBUG
            options.EnableDetailedErrors = true;
#else
            options.EnableDetailedErrors = false;
#endif
        })
        .AddAzureSignalR(options =>
        {
            options.ServerStickyMode = ServerStickyMode.Required;
            options.ConnectionString = uri;
        });

        services.AddScoped(options =>
        {
            var navigationManager = options.GetRequiredService<NavigationManager>();
            var tokenProvider = options.GetRequiredService<TokenProvider>();

            var hubConnection = new HubConnectionBuilder()
                .WithUrl(navigationManager.ToAbsoluteUri($"/hub?user={tokenProvider.UserId}"), config =>
                {
                    config.Headers.Add("X-User-ID", tokenProvider.UserId.ToString());
                    config.SkipNegotiation = false;

                    if (tokenProvider.Cookies.IsNotNullOrEmpty())
                    {
                        var cookieCount = tokenProvider.Cookies.Count;
                        var cookieContainer = new CookieContainer(cookieCount);

                        tokenProvider.Cookies.ToList().ForEach(cookie =>
                        {
                            cookieContainer.Add(new Cookie(cookie.Key, WebUtility.UrlEncode(cookie.Value), path: "/", domain: navigationManager.ToAbsoluteUri("/").Host));

                            config.Headers.Add(cookie.Key, cookie.Value);
                        });

                        config.Cookies = cookieContainer;
                        config.UseDefaultCredentials = true;
                        config.HttpMessageHandlerFactory = (source) =>
                        {
                            var clientHandler = new HttpClientHandler()
                            {
                                PreAuthenticate = true,
                                CookieContainer = cookieContainer,
                                UseCookies = true,
                                UseDefaultCredentials = true
                            };

                            return clientHandler;
                        };
                    }
                })
                .WithAutomaticReconnect()
                .ConfigureLogging(logging =>
                {
                    logging.AddConsole();
                    logging.AddDebug();
#if DEBUG
                    logging.SetMinimumLevel(LogLevel.Error);
#else
                    logging.SetMinimumLevel(LogLevel.None);
#endif
                })
                .Build();

            return hubConnection;
        });

        return services;
    }
}
```

When connecting to the hub when passing my bearer token I get this exception, which tells me the negotationresponse fails.

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.proxicare.smartyglass, PID: 5400
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.proxicare.smartyglass/com.proxicare.smartyglass.MainActivity}: java.lang.RuntimeException: Error reading NegotiateResponse
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.RuntimeException: Error reading NegotiateResponse
        at com.microsoft.signalr.NegotiateResponse.<init>(NegotiateResponse.java:86)
        at com.microsoft.signalr.HubConnection.lambda$handleNegotiate$1(HubConnection.java:175)
        at com.microsoft.signalr.HubConnection$$ExternalSyntheticLambda41.apply(Unknown Source:4)
        at io.reactivex.rxjava3.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:58)
        at io.reactivex.rxjava3.subjects.SingleSubject.onSuccess(SingleSubject.java:141)
        at com.microsoft.signalr.DefaultHttpClient$2.onResponse(DefaultHttpClient.java:156)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 6 column 1 path $
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562)
        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1403)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:592)
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:378)
        at com.microsoft.signalr.NegotiateResponse.<init>(NegotiateResponse.java:25)
        at com.microsoft.signalr.HubConnection.lambda$handleNegotiate$1(HubConnection.java:175) 
        at com.microsoft.signalr.HubConnection$$ExternalSyntheticLambda41.apply(Unknown Source:4) 
        at io.reactivex.rxjava3.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:58) 
        at io.reactivex.rxjava3.subjects.SingleSubject.onSuccess(SingleSubject.java:141) 
        at com.microsoft.signalr.DefaultHttpClient$2.onResponse(DefaultHttpClient.java:156) 
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
Disconnected from the target VM, address: 'localhost:64562', transport: 'socket'	
```

Any help guiding me through this issue or helping me along the way of where I could start looking would be greatly appreciated.

**Comment by Y-Sindo** [comment]
Please see https://github.com/Azure/azure-signalr/tree/dev/samples/BlazorAppSample for a Blazor App sample.

There are a few misunderstandings in your code.
1. The `AddAzureSignalR` method is not related to middleware, instead, it handles [Dependency injection](https://learn.microsoft.com/aspnet/core/fundamentals/dependency-injection). To troubleshoot why your authentication and authorization don't work, you should look at your real middleware code. In the sample mentioned before, the SignalR-related middleware code is 
	```cs
	app.UseEndpoints(endpoints =>
	{
	    endpoints.MapBlazorHub();
	    endpoints.MapFallbackToPage("/_Host");
	    endpoints.MapHub<BlazorChatSampleHub>(BlazorChatSampleHub.HubUrl);
	});
	```
1. You shouldn't use the method to add authorization header by yourself as follows:
	```cs
			hubConnection = HubConnectionBuilder.create(connectionUrl)
                .withHeader("Authorization", token)
                .build();
	```
    Firstly, the syntax of authorization header with bear schema is `bear [YourRealToken]`. The built-in method `withAccessTokenProvider` handles the syntax for you.
1. In your hub methods `OnConnectedAsync` and `OnDisconnectedAsync`, it seems that you want to add the connection to a group named by the user ID and remove it accordingly. You don't have to do this by yourself. You just need to set the user ID in the correct way and the framework and SDK handles them for you. For how to set the user ID, see [Users in SignalR](https://learn.microsoft.com/aspnet/core/signalr/groups?view=aspnetcore-7.0#users-in-signalr)
2. Adding the `HubConnection` as a scoped service also confuses me.  The `HubConnection` is usually used in client side to create a client connection to SignalR service / server.

### FYI 
* [ASP.NET Core Middleware Overview](https://learn.microsoft.comaspnet/core/fundamentals/middleware/?view=aspnetcore-7.0)
* [Authorization Header](https://developer.mozilla.org/docs/Web/HTTP/Headers/Authorization)
* [Authentication and authorization in ASP.NET Core SignalR](https://learn.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-7.0)

**Comment by Roodem** [comment]
> 

Hi, thank you for taking the time to respond to my ticket.
I seem to have messed up my post regarding the java code im using. I've tried using both the withHeader method and the withAccessProvider method and tested it but that didnt work.  I've edited that in the post now.

My bearer token is an Auth0 bearer token, ive attempted to add the "Bearer " prefix to the token but that didnt work either.

The SignalR related middleware ive set up is this:

```
app.MapBlazorHub();
app.MapHub<MyHub >("/hub", options =>
{
    options.Transports = HttpTransportType.WebSockets;
});
app.MapFallbackToPage("/_Host");
```
As I'm still struggling with authentication in my java app, I will go through the documentation again. Feel free to give feedback if you see I'm doing something wrong.

**Comment by Y-Sindo** [comment]
I am suspecting that your bear token fails the authentication and authorization. What's the HTTP response to the negotiation requests? How do you set up your authentication and authorization middlewares? It would be better if you can provide a minimal reproducible project to the issue.
