### ISSUE TITLE
NuGet Microsoft.Azure.SignalR Version 1.29.0 throws System.MissingMethodException on startup

### ISSUE THREAD

**Issue by Yomodo** [Azure/azure-signalr#2100]
### Describe the bug
Using .NET 8, Azure Function in isolated worker mode.
After installing NuGet Microsoft.Azure.SignalR Version 1.29.0,  my code now throws:

![Image](https://github.com/user-attachments/assets/bb7f8a8c-8e00-4fd4-9346-1498bd458864)

### Exceptions (if any)
Full stack trace:

System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Microsoft.Azure.SignalR.AccessKey Microsoft.Azure.SignalR.ServiceEndpoint.get_AccessKey()'.
  Source=Microsoft.Azure.SignalR.Management
  StackTrace:
   at Microsoft.Azure.SignalR.Management.RestApiProvider..ctor(ServiceEndpoint endpoint)
   at Microsoft.Azure.SignalR.Management.ServiceManagerImpl..ctor(IReadOnlyCollection`1 services, IServiceProvider serviceProvider, RestClient restClient, IServiceEndpointManager endpointManager)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Azure.SignalR.Management.ServiceManagerBuilder.BuildServiceManager()
   at Program.<>c__DisplayClass0_0.<<<Main>$>b__2>d.MoveNext() in C:\Users\...

### Further technical details
- Microsoft.Azure.SignalR SDK 1.29.0
- Microsoft.AspNetCore.SignalR.Client.Core 8.0.10
- Microsoft.AspNetCore.SignalR.Client 8.0.10

**Comment by vicancy** [comment]
Thanks for reporting the issue, looks like introduced in by https://github.com/Azure/azure-signalr/pull/2066. The issue is caused when Microsoft.Azure.SignalR SDK is upgraded to 1.29.0 while the Microsoft.Azure.SignalR.Management SDK is still in old version.

Could you share why you are reference Microsoft.Azure.SignalR SDK 1.29.0 in serverless project, in a serverless project we usually reference Microsoft.Azure.SignalR.Management SDK 1.29.0?

Could you try adding reference to [Microsoft.Azure.SignalR.Management ](https://www.nuget.org/packages/Microsoft.Azure.SignalR.Management) 1.29.0 explicitly to your project to see if it mitigates the issue?

**Comment by terencefan** [comment]
Backwards compatibility fix, need to discuss.

#2103

**Comment by Yomodo** [comment]
I can confirm that installing Microsoft.Azure.SignalR.Management 1.29 resolves my issue.

We explicitly reference Microsoft.Azure.SignalR SDK 1.29.0 as a top-level package
to avoid using another version because of a transitive package level.
