### ISSUE TITLE
Exceptions in azure signalr service connection

### ISSUE THREAD

**Issue by sandipbhavsar** [Azure/azure-signalr#250]
Microsoft.Azure.SignalR.ServiceConnection|ERROR|Error receiving handshake response. System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at Microsoft.Azure.SignalR.ServiceConnectionBase.ReceiveHandshakeResponseAsync(PipeReader input, CancellationToken token)
   at Microsoft.Azure.SignalR.ServiceConnectionBase.HandshakeAsync()

**Comment by vicancy** [comment]
This error can happen when network issue took place.

Could you edit the issue with more detailed descriptions to help us identify the issue, with:
1. Versions of the SDK
2. Frequency and time range when the exception took place
3. The status of your app server during that period, or anything abnormal that worth noting
4. Any other valuable information is appreciated

**Comment by vicancy** [comment]
Please feel free to reopen the issue if you still have concerns about it.
