### ISSUE TITLE
OnDisconnectedAsync does not get called everytime

### ISSUE THREAD

**Issue by alexiordan** [Azure/azure-signalr#266]
Found following error in log. 
```
[Error]Error when dispatching '"OnDisconnectedAsync"' on hub. { EventId: { Id: 1, Name: "ErrorDispatchingHubEvent" }, SourceContext: "Microsoft.AspNetCore.SignalR.HubConnectionHandler" }
System.InvalidOperationException: The connection is not active, data cannot be sent to the service.
   at Microsoft.Azure.SignalR.ServiceConnectionBase.WriteAsync(ServiceMessage serviceMessage)
   at Microsoft.Azure.SignalR.ServiceConnectionManager`1.WriteAsync(String partitionKey, ServiceMessage serviceMessage)
   at CityPointWebApp.Hubs.BarrierHub.OnDisconnectedAsync(Exception exception) in C:\Users\Alex\Source\Repos\CityPointWebApp\CityPointWebApp\Hubs\BarrierHub.cs:line 93
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnDisconnectedAsync(HubConnectionContext connection, Exception exception)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.HubOnDisconnectedAsync(HubConnectionContext connection, Exception exception)
```

Any ideas?

**Comment by vicancy** [comment]
`WriteAsync(String partitionKey, ServiceMessage serviceMessage)`, this is a group related message, this message always goes into the same server-connection, the error can take place when this server-connection is not in a health mode, e.g. reconnecting...
We need to improve this to make it more robust.
