### ISSUE TITLE
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).

### ISSUE THREAD

**Issue by hempe** [Azure/azure-signalr#445]
I think the documentation in the [Troubleshooting Guide](https://github.com/Azure/azure-signalr/blob/4b25abd60b74a9d78569d0f3d01145bc84f989a2/docs/tsg.md#403-returned-for-client-requests) is not correct or not complete.
We set the AccessTokenLifetime to 30 minutes and got a 401 on the C# client side, instead of a 403.

```
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.SendUtils.<SendMessages>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<ReceiveLoop>d__62.MoveNext()
```

**Comment by vicancy** [comment]
401 should not be caused by setting `AccessTokenLifetime`. Could you provide more details how you get 401? What is the detailed error message of your 401?

**Comment by hempe** [comment]
Ok, for testing I set it now to 1 Minute and exactly after a minute HubConnection.Closed gets fired on the client side.


And this is everything I get. (@vicany Is there a way I can get the response body?)
```
"Message": Response status code does not indicate success: 401 (Unauthorized).
"Data": {}
"InnerException": null
"TargetSite": { System.Net.Http.HttpResponseMessage EnsureSuccessStatusCode() }
"StackTrace":
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.SendUtils.<SendMessages>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<ReceiveLoop>d__62.MoveNext(),
"Source": System.Net.Http
"HResult": -2146233088
```

About the client software
- .Net Framework 4.6.1
- Microsoft.AspNetCore.SignalR.Client v1.1.0
- HttpTransportType set to ServerSentEvents.

About the server software
- We use a custom authentication schema based on Microsoft.AspNetCore.Authentication.AuthenticationHandler<TOptions>
- HandleAuthenticateAsync gets called and works, but HandleChallengeAsync never gets called.

**Comment by vicancy** [comment]
Oh my bad, definitely it should be 401 Unauthorized. Thanks for reporting the issue.
