### ISSUE TITLE
Received close message with an error: "ServerOffline"

### ISSUE THREAD

**Issue by alexiordan** [Azure/azure-signalr#519]
Suddenly .Net UWP Client gets disconnected.

From client log it seems that server encountered some issues. However other clients connected to same server did not hit the same issues.

Any ideas why?

Sorry for the long log...  File version is also available if needed.
```
2019-04-30 03:36:47.069 +03:00 [Error] Received close message with an error: "Internal server error."
2019-04-30 03:36:47.471 +03:00 [Error] Error: The server closed the connection with the following error: Internal server error.
... (30 times)
2019-04-30 03:36:47.569 +03:00 [Error] Error: The server closed the connection with the following error: Internal server error.
2019-04-30 03:36:48.157 +03:00 [Error] Connection is shutting down due to an error.
Microsoft.AspNetCore.SignalR.HubException: The server closed the connection with the following error: Internal server error.
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at myLib.DN.ServiceLibrary.SignalRServerCommunicator.SendMessageAsync(ServerDnMessage message)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at myLib.DN.ServiceLibrary.SignalRServerCommunicator.SendMessageAsync(ServerDnMessage message)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at myLib.DN.ServiceLibrary.SignalRServerCommunicator.SendMessageAsync(ServerDnMessage message)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at myLib.DN.ServiceLibrary.SignalRServerCommunicator.SendMessageAsync(ServerDnMessage message)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at myLib.DN.ServiceLibrary.SignalRServerCommunicator.SendMessageAsync(ServerDnMessage message)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at myLib.DN.ServiceLibrary.SignalRServerCommunicator.SendMessageAsync(ServerDnMessage message)
... (10 times)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at myLib.DN.ServiceLibrary.SignalRServerCommunicator.SendMessageAsync(ServerDnMessage message)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at myLib.DN.ServiceLibrary.SignalRServerCommunicator.SendMessageAsync(ServerDnMessage message)
2019-04-30 03:36:48.496 +03:00 [Error] HubConnection_Closed Exception
2019-04-30 07:44:59.052 +03:00 [Error] Received close message with an error: "ServerOffline"
2019-04-30 07:44:59.265 +03:00 [Error] Connection is shutting down due to an error.
Microsoft.AspNetCore.SignalR.HubException: The server closed the connection with the following error: ServerOffline
2019-04-30 07:44:59.267 +03:00 [Error] HubConnection_Closed Exception
2019-04-30 09:29:22.811 +03:00 [Error] Received close message with an error: "ServerOffline"
2019-04-30 09:29:22.828 +03:00 [Error] Error: The server closed the connection with the following error: ServerOffline
```

**Comment by vicancy** [comment]
Any server side error log such as `Connection "..." to the service was dropped`?
This `ServerOffline` error code indicates that the server connection carrying this client is dropped. Such server connection drop are generally transient ones, they can happen when the service deploys, underlying Azure infra maintenance happens, or intermediate network issues. As a best practice, we suggest client side having continuous reconnect logic to handle such connection drop, as shown in the sample code:

https://github.com/Azure/azure-signalr/blob/b48ab1ddbf43d087382f2b96a4bff2e8c41d3d28/samples/ChatSample/ChatSample.CSharpClient/Program.cs#L55-L56

The impact of server connection drop depends on how many client connections are routed to this server connection. Generally we think it meets the service SLA if it does not happen frequently (like several times a day) and the server connections recover soon after the drop.

**Comment by alexiordan** [comment]
Unfortunately I don't have server logs from that day anymore.

It is nice to see that there is an explanation for such behavior.
I have a reconnect logic, but thank you for sharing that sample resource.

If will happen more frequently than I will reopen this.

Thank you!

**Comment by alexiordan** [comment]
I get this kind of error daily at around `2019-05-20T01:35:24.303Z`
Several clients got same kind of error, and afterwards reconnected.
1. Is this something planned to happen each day at that hour so I shouldn't consider it error?
2. There are many such errors. About 30 errors per client between '2019-05-20T01:35:23.767 - 2019-05-20T01:35:27.185.
```
Microsoft.AspNetCore.SignalR.HubException
The server closed the connection with the following error: Internal server error.
at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   
```

**Comment by vicancy** [comment]
Hi @alexiordan , client connections can drop for various errors. Please refer to https://github.com/Azure/azure-signalr/blob/dev/docs/tsg.md#%EF%B8%8Ftodoclient-connection-drop for troubleshooting guidance. If there were no events from your app server side, please send me an email about the period the issue took place and your Azure SignalR instance name for me to check from service side.

**Comment by alexiordan** [comment]
There are no `Connection "..." to the service was dropped` errors.
However there are calls to OnDisconnected at 2019-05-20T01:35:23.

On those OnDisconnected my app crashed - I will fix that.

But why where all those clients disconnecting? 
I've sent you an e-mail with required information.

**Comment by vicancy** [comment]
Network issues can also cause client connection drops. Where are the clients hosted? If the clients are not in a stabled network environment, it is normal that they experience disconnect.

**Comment by alexiordan** [comment]
Clients are in diverse environments. Some are connected over 4G modems, while others wired. There are different ISPs involved.
I cannot believe it is a coincidence that 4 clients as described above got disconnected at same time...

**Comment by alexiordan** [comment]
As we speak there is a lot of instabillity server side. Many clients receive 
`Error: Server timeout (10000.00ms) elapsed without receiving a message from the server.`
I have set the server to send pings each 4 seconds with a 10 seconds timeout interval. And during last hour most of my clients encountered such errors.
