### ISSUE TITLE
Client cannot reconnect although ping was working fine

### ISSUE THREAD

**Issue by alexiordan** [Azure/azure-signalr#525]
Client got disconnected.
While pings to www.google.com worked flawlessly, attempts to connect to SignalR service failed with  _A connection with the server could not be established_ error.

Server side logs don't show anything abnormal.
Other clients didn't disconnect in that period of time.

What could cause such behavior?
Client log fragment below:
```
2019-05-09T09:49:34.457Z Error: Server timeout (10000.00ms) elapsed without receiving a message from the server.
===Retrying to connect after a while===
2019-05-09T09:49:48.63Z  A connection with the server could not be established 
 at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.AccessTokenHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.GetNegotiationResponseAsync(Uri uri)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HttpConnectionFactory.ConnectAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HttpConnectionFactory.ConnectAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
   at utpark.DN.ServiceLibrary.SignalRClient.StartConnectionAsync()

```

**Comment by vicancy** [comment]
How many clients met such error? You can email me the time when the issue took place, and your instance name so that I can check from the service side log to see if there were anything abnormal.

**Comment by alexiordan** [comment]
1 client only. I sent over the e-mail required details.
I also mentioned in e-mail, but I'll post here also for future reference:

**1. Time the issue took place**
9th of May 2019 between 09:49 UTC and 10:21 UTC. 

I first encountered a disconnect at 9:49 UTC. I was able to successfully reconnect to SignalR Service at 10:21 UTC
My reconnect logic makes retries at following intervals:

- 2 s
- 4 s
- 8 s
- 16 s
- 32 s
- 64 s
- 128 s
- 256 s
- 256 s
- ....

**2. Additional information**
I use [Azure Log Analytics](https://docs.microsoft.com/en-us/rest/api/loganalytics/) (REST calls to Azure service, not my app)  to centralize logs from clients. In those logs I can see records that seems to be locally generated during the offline period, but received in Azure Log Analytics at 10:19 UTC.

That makes me believe that something happened, but client reconnected only 2 minutes after connection to Azure was re-established, given my reconnect logic, .

**Comment by vicancy** [comment]
So sounds like the client is having trouble connecting to both Azure Log Analytics and Azure SignalR between 09:49 UTC and 10:21 UTC.

From service side log, we can see one client ended normally on 2019-05-09T09:49:45 UTC, we can also see continuously client requests coming in at 2019-05-09T10:00:16, 2019-05-09T10:00:24.... So I am wondering if the network issue happens from the client side, or in between that specific client to Azure. If the problem can be repro-ed, run `tracert <service>.service.signalr.net` from client side can help identify the network issue.

**Comment by alexiordan** [comment]
Thank you for taking a look.
When you say:

> we can also see continuously client requests coming in at 2019-05-09T10:00:16, 2019-05-09T10:00:24.... 

1. You are talking about other clients, right?


It would be hard to reproduce. 
However we can ping both to google.com and something_in_azure.net, to see whether both fail or not.

2. Just to see there is something in between, that keeps the client from reaching the server, ping should be as effective, right? 
We'll try to enable tracert if offline for longer time, but not that the ping is fastest to implement.

3. What address you suggest we should ping? `<service>.service.signalr.net` does not reply to pings. Beside that, given we had trouble connecting to Azure Log Analytics too, maybe we can ping something else that covers both (in West Europe Azure) ?

**Comment by vicancy** [comment]
> You are talking about other clients, right?

Yes

> Just to see there is something in between, that keeps the client from reaching the server, ping should be as effective, right?

Just realized that ping/tracert is blocked by azure. You can use [tcping](https://elifulkerson.com/projects/tcping.php)

> maybe we can ping something else that covers both

Not aware of that. If your client is having issue accessing all azure services, try opening a support ticket in azure portal to the Azure network team.

**Comment by vicancy** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
