### ISSUE TITLE
ASP.Net SignalR - exception with Microsoft.Extensions.Logging.EventSource v3.0.0

### ISSUE THREAD

**Issue by marshall76963** [Azure/azure-signalr#740]
When using the latest version of `Microsoft.Extensions.Logging.EventSource`  (version 3.0.0) which was released recently, SignalR for ASP.Net fails with the following exception captured in the EventLog:

```C#
Exception has been thrown by the target of an invocation. 
	at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) 
	at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) 
	at Owin.Loader.DefaultLoader.<>c__DisplayClass18_1.<MakeDelegate>b__0(IAppBuilder builder) 
	at Owin.Loader.DefaultLoader.<>c__DisplayClass9_0.<LoadImplementation>b__0(IAppBuilder builder) 
	at Microsoft.Owin.Host.SystemWeb.OwinHttpModule.<>c__DisplayClass5_0.<InitializeBlueprint>b__0(IAppBuilder builder) 
	at Microsoft.Owin.Host.SystemWeb.OwinAppContext.Initialize(Action`1 startup) 
	at Microsoft.Owin.Host.SystemWeb.OwinBuilder.Build(Action`1 startup) 
	at Microsoft.Owin.Host.SystemWeb.OwinHttpModule.InitializeBlueprint() 
	at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory) 
	at Microsoft.Owin.Host.SystemWeb.OwinHttpModule.Init(HttpApplication context) 
	at System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) 
	at System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) 
	at System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) 
	at System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) Method not found: 'Microsoft.Extensions.Logging.ILoggerFactory Microsoft.Extensions.Logging.EventSourceLoggerFactoryExtensions.AddEventSourceLogger(Microsoft.Extensions.Logging.ILoggerFactory)'.
	at Owin.OwinExtensions.RunAzureSignalRCore(IAppBuilder builder, String applicationName, HubConfiguration configuration, ServiceOptions options)
	at Owin.OwinExtensions.RunAzureSignalR(IAppBuilder builder, String applicationName, HubConfiguration configuration, Action`1 optionsConfigure)
	at Owin.OwinExtensions.<>c__DisplayClass6_0.<MapAzureSignalR>b__0(IAppBuilder subApp)
	at Owin.MapExtensions.Map(IAppBuilder app, PathString pathMatch, Action`1 configuration)
	at Owin.MapExtensions.Map(IAppBuilder app, String pathMatch, Action`1 configuration)
	at Owin.OwinExtensions.MapAzureSignalR(IAppBuilder builder, String path, String applicationName, HubConfiguration configuration, Action`1 optionsConfigure) 
	at Owin.OwinExtensions.MapAzureSignalR(IAppBuilder builder, String applicationName, HubConfiguration configuration, Action`1 optionsConfigure) 
	at Startup.Configuration(IAppBuilder app)
```

We are running an ASP.Net App Service in Azure backed by an Azure SignalR instance cofigured in Default mode.

I have tested this avaing Microsoft.Azure.SignalR.AspNet versions 1.2.0 and 1.2.1, and both produce the same issue (however there is no issue when running locally).

It appears that the Logging API has changed and the method has been removed or had its signature changed - the following line from the above stack trace appears to be the culprit:
```C#
System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) Method not found: 'Microsoft.Extensions.Logging.ILoggerFactory Microsoft.Extensions.Logging.EventSourceLoggerFactoryExtensions.AddEventSourceLogger(Microsoft.Extensions.Logging.ILoggerFactory)'.
```

Can you please review the ASP.Net SignalR service against the latest `Microsoft.Extensions.Logging.EventSource` and confirm if this is a real issue or if I could be missing something?  For now we can run against an earlier version of the library, but it would be good to be able to support the lastest version.

Many thanks

**Comment by marshall76963** [comment]
Quick update - the issue persists with the latest version of `Microsoft.Extensions.Logging.EventSource` (version 3.0.1) which was released today along with a number of other extension libraries at the same version.

**Comment by vicancy** [comment]
`3.0.0` removes extension method `public static ILoggerFactory AddEventSourceLogger(this ILoggerFactory factory)`

**Comment by vicancy** [comment]
v1.2.2 is planned to be released next week to fix this issue. The current 1.2.2 preview package should already contain the fix. 

```ps
Install-Package Microsoft.Azure.SignalR.AspNet -Version 1.2.2-preview1-10501 -Source https://www.myget.org/F/azure-signalr-dev/api/v3/index.json
```
