### ISSUE TITLE
MapFallbackToController causes issue with Hub Negotiation in Core 3.0

### ISSUE THREAD

**Issue by tjkb** [Azure/azure-signalr#777]
We are currently migrating a production SPA that leverages Azure SignalR from .Net Core 2.2 to 3.0. Our startup looks like this:

```
app.UseEndpoints(endpoints =>
	{
		endpoints.MapDefaultControllerRoute();
		endpoints.MapFallbackToController("Index", "Home");
		endpoints.MapHub<CustomHub>("/customhub");
	}
});
```

Starting the app we run into this error when the client tries to negotiate:
```
System.InvalidCastException: Unable to cast object of type 'Microsoft.AspNetCore.Http.Endpoint' to type 'Microsoft.AspNetCore.Routing.RouteEndpoint'.
   at Microsoft.Azure.SignalR.NegotiateMatcherPolicy.CreateNegotiateEndpoint(Endpoint endpoint)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Azure.SignalR.NegotiateMatcherPolicy.ApplyAsync(HttpContext httpContext, CandidateSet candidates)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Without the line `endpoints.MapFallbackToController("Index", "Home");` it works, however we need this for our SPA. 

In .Net Core 2.2 it was working as expected.

**Comment by JialinXin** [comment]
@tjkb Thanks for reporting the issue. I did a check on the method `MapFallbackToController` but seems it's only available after .Net Core 3.0. From the exception message, it seems there's `Endpoint` class conflict between different libraries. Would you share more information about where dependencies you're using and how's it in the startup before and after you do the upgrade.

**Comment by tjkb** [comment]
Yes, `MapFallbackToController` is new in .Net Core 3.0. It replaces `MapSpaFallbackRoute`. 

Startup before (.Net Core 2.2)
```
app.UseMvc(routes =>
{
  routes.MapRoute("default", "{controller=Home}/{action=Index}/{id?}");
  routes.MapSpaFallbackRoute("spa-fallback", new { controller = "Home", action = "Index" });
});
app.UseAzureSignalR(routes =>
{
  routes.MapHub<CustomHub>("/customhub");
});
```
Startup now (.Net Core 3.0)
```
app.UseEndpoints(endpoints =>
{
  endpoints.MapDefaultControllerRoute();
  endpoints.MapFallbackToController("Index", "Home");
  endpoints.MapHub<CustomHub>("/customhub");
});
```
The target framework is `netcoreapp3.0` and we use 
```
<PackageReference Include="Microsoft.Azure.SignalR" Version="1.2.2" />
```

Thanks for looking into this. Please let me know if you need more information about the our project.

**Comment by tjkb** [comment]
@JialinXin  thanks for fixing it

**Comment by JialinXin** [comment]
@tjkb Just an update that version 1.2.3 is released. Please update to latest for the fix.

**Comment by davidfowl** [comment]
Nice fix @JialinXin !
