### ISSUE TITLE
Version 1.4.0 not working when using .netcore 2.2

### ISSUE THREAD

**Issue by Grompie** [Azure/azure-signalr#840]
Not sure if I misinterpreted this but I was using a .net core 2.2 as host project in combination with a .net standard 2.0 library. Both used version 1.4.0 of the nuget package. I checked all the logs and it seems my project was able to connect to the azure signalr service but the server never received the OnConnectedAsync.

It was only after I made a new project to test out if it was some other code that was bothering me that I found out that it only works if the host project uses .netcore 3.1 (didn't test 3.0).

I switched back to version 1.0.15 on my main project where I want to use signalr service and this seems to have fixed my issues.
Is .netcore 2.2 not "supported" for this library anymore or is something broken? I thought since it's .net standard 2.0 this still should work on .netcore 2.2

**Comment by vicancy** [comment]
Quick workaround:
---
Add an explicit package reference to the assembly:
```xml
<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.7.0" />
```
-------------
Thanks for reporting the issue! I am able to repro it with `netcoreapp2.2`.
LTS versions `netcoreapp2.1`, `netcoreapp3.0` and `netcoreapp3.1` are working as expected.

`netcoerapp2.2` fails with assembly resolving issue: 
> System.IO.InvalidDataException: Reading map length for 'headers' failed. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.Buffers.SequenceReaderExtensions.TryRead[T](SequenceReader`1& reader, T& value)
   at System.Buffers.SequenceReaderExtensions.TryReadReverseEndianness(SequenceReader`1& reader, Int16& value)
   at MessagePack.MessagePackReader.TryReadMapHeader(Int32& count)
   at Microsoft.Azure.SignalR.Protocol.ServiceProtocol.ReadMapLength(MessagePackReader& reader, String field)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.SignalR.Protocol.ServiceProtocol.ReadMapLength(MessagePackReader& reader, String field)
   at Microsoft.Azure.SignalR.Protocol.ServiceProtocol.ReadHeaders(MessagePackReader& reader)
   at Microsoft.Azure.SignalR.Protocol.ServiceProtocol.CreateOpenConnectionMessage(MessagePackReader& reader, Int32 arrayLength)
   at Microsoft.Azure.SignalR.Protocol.ServiceProtocol.ParseMessage(MessagePackReader& reader)
   at Microsoft.Azure.SignalR.Protocol.ServiceProtocol.TryParseMessage(ReadOnlySequence`1& input, ServiceMessage& message)
   at Microsoft.Azure.SignalR.ServiceConnectionBase.ProcessIncomingAsync(ConnectionContext connection)

This issue is introduced in when we removed external dep to MessagePack in https://github.com/Azure/azure-signalr/pull/803 

To quickly workaround the issue, please add an explicit package reference to the assembly:
```xml
<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.7.0" />
```

We will investigate to solve the issue from the SDK side and let you updated if there is any progress.

**Comment by vicancy** [comment]
Meanwhile, we need to improve our nightly build to cover the case, going through all the available frameworks. cc @wanlwanl @chenkennt

**Comment by wanlwanl** [comment]
Yes, will check and improve the our nightly build.
