### ISSUE TITLE
Mock/disable SignalR in tests

### ISSUE THREAD

**Issue by dorfire** [Azure/azure-signalr#867]
In integration tests, I run an ASP.NET Core 3 app, and replace some external services with mocks/fakes using `WebHostBuilderExtensions.ConfigureTestServices`.

When running the test, I get:

```
Error Message:
   Microsoft.Azure.SignalR.Common.AzureSignalRConfigurationNoEndpointException : No connection string was specified.
  Stack Trace:
     at Microsoft.Azure.SignalR.ServiceEndpointManagerBase.GetValuableEndpoints(IEnumerable`1 endpoints)
   at Microsoft.Azure.SignalR.ServiceEndpointManagerBase..ctor(IEnumerable`1 endpoints, ILogger logger)
   at Microsoft.Azure.SignalR.ServiceEndpointManagerBase..ctor(IServiceEndpointOptions options, ILogger logger)
   at Microsoft.Azure.SignalR.ServiceEndpointManager..ctor(IOptionsMonitor`1 optionsMonitor, ILoggerFactory loggerFactory)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
[...]
```

What's the recommended approach to mock/fake/disable SignalR for the integration tests?

**Comment by vicancy** [comment]
> In contrast to unit tests, integration tests:
> 
> Use the **actual components that the app uses in production**.

*Quoted from https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1#introduction-to-integration-tests)*

So for integration test you might need to provide one Azure SignalR endpoint acting as a test endpoint.

**Comment by vicancy** [comment]
Closing the issue, please reopen it if you have any additional concerns.
